### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by imlanky** [thekevinscott/UpscalerJS#554] opened 2022-10-28 13:30 UTC
```
/node_modules/upscaler/dist/browser/esm/index.js:1
export { default, } from './upscaler';
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by thekevinscott** [comment] 2022-10-28 14:58
Can you provide a reproducible repository?

An issue like this is usually related to how your bundle or transpiler is set up. You're loading ESM code but whatever setup is complaining that it doesn't know how to handle it.

**Comment by thekevinscott** [comment] 2022-11-12 15:21
Closing for now, feel free to reopen with a reproducible repo

**Comment by thekevinscott** [comment] 2022-12-07 13:42
@hollowshiroyuki I can’t access that repo - maybe it’s set to private?

**Comment by hollowshiroyuki** [comment] 2022-12-08 13:38
whoops sorry, it's fixed now :+1:

**Comment by thekevinscott** [comment] 2022-12-08 14:38
Thanks, I can see it now. 

I’m on my phone and can check later, but at a glance - is this a Node.js project? If so you’ll need to import from node:

Import ‘upscaler/node’

check out the getting started docs section on node. 

I’ll double check again when I’m front of my computer

**Comment by hollowshiroyuki** [comment] 2022-12-08 16:26
This is indeed a nodejs project and I'm using Typescript.

I tried your suggestion but it didn't work, I'm not sure if it's a problem of the package or my typescript configuration.

I also tried using [https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) without success.

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "upscaler": ["node_modules/upscaler/dist/node"],
    }
  }
}
```

**Comment by thekevinscott** [comment] 2022-12-09 10:09
I opened https://github.com/hollowshiroyuki/Timi_OCR_Proto/pull/1/files which should resolve the issues you're seeing (I'm not familiar TesseractJS, but the script completes without errors).

Some things:

- [You need to install `@tensorflow/tfjs-node`](https://github.com/hollowshiroyuki/Timi_OCR_Proto/pull/1/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R19) as an explicit dependency alongside UpscalerJS
- [You need to use `require` to load Upscaler in a Node environment](https://github.com/hollowshiroyuki/Timi_OCR_Proto/pull/1/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R5) - more on this below
- The output of an upscale operation is either a base64 string or a tensor. For your purposes (I think TesseractJS expects a file on disk) [you're better off returning a tensor and saving it to disk](https://github.com/hollowshiroyuki/Timi_OCR_Proto/pull/1/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R22). Base64 outputs are more useful in a browser experience for easy display in an `<img />` tag.

----

On the subject of needing to load the Node version with `require`: we bundle the library in a few flavors:

- ESM (browser only)
- CJS (node only)
- UMD (browser only)

Which has been roughly sufficient, as most Node projects can consume CJS (either because they're written in CJS themselves, or can use a transpiler) and most browser-based projects can consume either ESM (via a transpiler) or load the UMD script tag.

It gets a bit trickier with the use of a tool like `ts-node`, which, as far as I understand, is transpiling your ESM Node source code on the fly with `tsc` into CommonJS, but which is expecting imported libraries to _also_ be ESM.

The reason I haven't provided an ESM-compatible Node version of the library so far is [that Node _also_ supports native ESM](https://nodejs.org/api/esm.html), but via the use of `.mjs` extensions, which (in the limited investigation I did) wrecked havoc with the existing build process.

That said, this is good motivation to pick that investigation back up, as you probably are not the only one who will run into that issue (and it's weird to need a single `require()` tag amongst the other `import` tags).

**Comment by hollowshiroyuki** [comment] 2022-12-15 13:55
Indeed it works now, we got better recognition performance, thanks a lot !

**Comment by thekevinscott** [comment] 2022-12-20 12:53
Awesome, great to hear!

One other thing I should have mentioned, because you're in Node, you should experiment with providing an explicit model. [I'd recommend either the 4x or 8x models from `esrgan-thick`](https://upscalerjs.com/models/available/esrgan-thick) (the 8x image is not shown, which is a bug in the documentation, but you should be able to import it). You can also explicitly specify the model you're using now, [`GANS` from `esrgan-legacy`](https://upscalerjs.com/models/available/esrgan-legacy?metrics=PSNR&datasets=Div2K&devices=iPhone+14+Pro+Max#available-models).

The reason I recommend this is because UpscalerJS is using the `default-model` by default, which currently is the GANS model (slow and more precise) but which will be switching to the 2x `esrgan-slim` model (fast, less precise). For your use case, I think you probably want the most precise model.

**Closed by thekevinscott** 2022-12-20 12:53 UTC
